#!/bin/bash
# Update the system
sudo apt update

# Install Docker dependencies
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

# Add Docker's official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the package index
sudo apt update

# Install Docker
sudo apt install -y docker-ce docker-ce-cli containerd.io

# Step 1: Change the hostname of the node
sudo hostnamectl set-hostname node01
# change the name of node if you have more than one node in other bash scripts
#sudo hostnamectl set-hostname node (X)
# Step 2: Create user ansible with password ansible and give sudo permission
sudo useradd -m -s /bin/bash -c "ansible" ansible
sudo echo "ansible:ansible" | sudo chpasswd
sudo echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
# Step 3: Create SSH keys for user ansible 
sudo -u ansible ssh-keygen -t rsa -N "" -f /home/ansible/.ssh/id_rsa
# Step 4: Edit sshd_config
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/' /etc/ssh/sshd_config
sudo sed -i 's/^#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
# Step 5: Restart sshd service
sudo systemctl restart sshd
# Add the current user to the 'docker' group
sudo usermod -aG docker ansible