name: Docker Container CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_IMAGE_NAME: app
  DOCKER_IMAGE_TAG: v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container on localhost
        run: |
          docker run -d --name app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Wait for container to start
        run: sleep 10s

      - name: Get container IP address
        id: container
        run: echo "::set-output name=ip::$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app)"

      - name: Open container in browser
        run: |
          container_ip=${{ steps.container.outputs.ip }}
          echo "Container IP: $container_ip"
          open "http://$container_ip:3000"
