name: Docker Container CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_IMAGE_NAME: app
  DOCKER_IMAGE_TAG: v2
  INSTANCE_IP: 54.242.177.166
  INSTANCE_USER: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create private key file
        run: |
          echo "${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Connect to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.INSTANCE_USER }}@${{ env.INSTANCE_IP }} 'docker run -d --name app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}'
